const weapons = [
    { "name": "12g Automatic" },
    { "name": "AG M42" },
    { "name": "BAR M1918A2" },
    { "name": "Boys AT Rifle" },
    { "name": "Breda M1935 PG" },
    { "name": "Bren Gun" },
    { "name": "Chauchat" },
    { "name": "Commando Carbine" },
    { "name": "EMP" },
    { "name": "FG-42" },
    { "name": "Gewehr 1-5" },
    { "name": "Gewehr 43" },
    { "name": "Gewehr M9530" },
    { "name": "Jungle Carbine" },
    { "name": "K3143" },
    { "name": "Kar98k" },
    { "name": "Karabin 1938M" },
    { "name": "KE7" },
    { "name": "Krag-Jorgensen" },
    { "name": "Lee-Enfield No4 Mk1" },
    { "name": "Lewis Gun" },
    { "name": "Liberator" },
    { "name": "LS26" },
    { "name": "M1 Garand" },
    { "name": "M1A1 Carbine" },
    { "name": "M2 Carbine" },
    { "name": "M3 Grease Gun" },
    { "name": "M3 Infrared" },
    { "name": "M28 Tromboncino" },
    { "name": "M30 Drilling" },
    { "name": "M97" },
    { "name": "M1907 SF" },
    { "name": "M1911 Suppressed" },
    { "name": "M1911" },
    { "name": "M1919A6" },
    { "name": "M1922 MMG" },
    { "name": "M1928A1" },
    { "name": "M1941 Johnson" },
    { "name": "MAB 38" },
    { "name": "Madsen MG" },
    { "name": "MAS 44" },
    { "name": "MG34" },
    { "name": "MG42" },
    { "name": "Mk VI Revolver" },
    { "name": "Model 8" },
    { "name": "Model 27" },
    { "name": "Model 37" },
    { "name": "MP28" },
    { "name": "MP34" },
    { "name": "MP40" },
    { "name": "P08 Carbine" },
    { "name": "P08 Pistol" },
    { "name": "P38 Pistol" },
    { "name": "Panzerbuchse 39" },
    { "name": "PPK Suppressed" },
    { "name": "PPK" },
    { "name": "Repetierpistole M1912" },
    { "name": "Ribeyrolles 1918" },
    { "name": "Ross Rifle Mk III" },
    { "name": "RSC" },
    { "name": "Ruby" },
    { "name": "S2-200" },
    { "name": "Selbstlader 1906" },
    { "name": "Selbstlader 1916" },
    { "name": "Sjogren Shotgun" },
    { "name": "STEN" },
    { "name": "StG 44" },
    { "name": "Sturmgewehr 1-5" },
    { "name": "Suomi KP-31" },
    { "name": "Trench Carbine" },
    { "name": "Turner SMLE" },
    { "name": "Type 2A" },
    { "name": "Type 11 MG" },
    { "name": "Type 94" },
    { "name": "Type 97 MG" },
    { "name": "Type 99 Arisaka" },
    { "name": "Type 100" },
    { "name": "VGO" },
    { "name": "Welgun" },
    { "name": "Welrod" },
    { "name": "ZH-29" },
    { "name": "Zk-383" }
];